@baseUrl = http://localhost:8000

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "johnde@example.com",
    "password": "mypassword"
}

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "firstName": "JD",
  "lastName": "Dk",
  "email": "johndoe3@ff.com",
  "password": "mypassword",
  "confirmPassword": "mypassword"
}
