@baseUrl = http://localhost:8000

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "mypassword"
}

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "firstName": "Jo",
  "lastName": "Do",
  "email": "johndoe1@example.com",
  "password": "mypassword"
}

### Logout
POST {{baseUrl}}/users/logout
Content-Type: application/json